# Generated by Django 5.1.3 on 2024-11-05 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0003_alter_product_status'),
        ('user_management', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_management.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='user_management.OrderItem', to='stock_management.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
