# Generated by Django 5.1.3 on 2024-11-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_number', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField()),
                ('vendor_phone_number', models.CharField(max_length=15)),
                ('vendor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
