# Generated by Django 5.1.2 on 2024-10-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('buying_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
