# Generated by Django 5.1.2 on 2024-10-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('packet', 'Packet'), ('litre', 'Litre'), ('piece', 'Piece')], default='piece', max_length=10),
        ),
    ]
