# Generated by Django 5.1.3 on 2024-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_management', '0002_product_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='blocked', max_length=10),
        ),
    ]
